/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-15-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public  class ArthimaticCalculations {
 public void Addition(integer x, integer y) {
        integer z = x + y;
 System.debug('Sum of variables ' + z);  }
   
   
 public void Subtraction(integer x, integer y){
            integer z = x - y;
 System.debug('Sum of variables ' + z);
        }


public integer Multiplication(integer x, integer y, integer m){
            integer z = x * y * m; 
System.debug('The multiplication of variables is '+ z);
    return z;
           }
}

