/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-22-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public  class Collections {

    public static string listaAssignment(integer i) {
    List<string> LstMonth = new List<string>();
    
    string outputMonth;
       
    LstMOnth.add('January');
    LstMOnth.add('february');
    LstMOnth.add('March');
    LstMOnth.add('April');
    LstMOnth.add('May');
    LstMOnth.add('June');
    system.debug(LstMOnth);
    LstMOnth.add('July');
    LstMOnth.add('August');
    LstMOnth.add('September');
    LstMOnth.add('October');
    LstMOnth.add('November');
    LstMOnth.add('December');
    
    system.debug(LstMOnth);


if (i < 0 || i > LstMonth.size()) {
     System.debug('not a valid month');
  } 
   return outputmonth = LstMOnth[i-1];
    
  }


 }
  
     
  
        
    
    

     
   

    
     
    
        
        
       

    
  



















