/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-22-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class ForEachLoopDemo1 {
    public static void ForEachLoopDemo1(){
        List<integer> listInteger = new List<integer>();
listInteger.add(10);
listInteger.add(15);
listInteger.add(21);
listInteger.add(32);
listInteger.add(100);

  
for (integer eachInteger: ListInteger) {
    system.debug(eachInteger);
}
}
}


    

