/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-19-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class Loops_Assignment {
    public void  Forloops(integer n) {

integer i = 0;
        while (i <= n) {
            system.debug (i);
            i ++;
        }
    }

public void printEven (integer b){
  
    integer i = 0;
        while (i <= b ){
        if (math.mod(i,2)==0){
            system.debug(i );
        }
           i++; 
        } 
    }
}





