/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-13-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class Player {
    public void playing() {
        string player1 = 'Alex';
        string player2 = 'Wilson';
        string player3 = ' John';
        string player4 = 'Anna';
        string player5 = 'Nancy';
        System.debug( player1);
        System.debug(player2);
        System.debug(player3);
        System.debug(player4);
        System.debug(player5);
        
        

    }
}
