/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-20-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class Students {
    public string FirstName;
    public string LastName;
    public integer ClassYear;
    public string MajorStream;
    public string generateReport(){
         
 System.debug('Report generated for ' + FirstName + LastName + ClassYear);

        return MajorStream;
    }



    
}
