/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-13-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class SundayProject{
    public void TeamDescription() {
        
      System.debug('The tennis is my favorite sport');
      System.debug(' Tennis was originated in France in the 12th century');


    }
}